process.env.REDIRECT_URL = "https://redirect"
process.env.DISCOVERY_ENDPOINT = "https://discovery"
process.env.CLIENT_ID = "clientid"
process.env.SESSION_TABLE_NAME = 'MYTABLE'
process.env.ACCOUNTS_DASHBOARD = 'https://home.staging.account.gov.uk/'
//export REDIRECT_URL="https://redirect"
//export DISCOVERY_ENDPOINT="https://discovery"
//export CLIENT_ID="clientid"
//export SESSION_TABLE_NAME='MYTABLE'
