version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "ipvreturn-front"
s3_prefix = "ipvreturn-front"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc-cri\""
image_repositories = []
confirm_changeset = false
