name: Build Node server build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

# To be used when the container signer stack is setup through the Terraform code in di-ipv-cri-pipeline-deployment
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     timeout-minutes: 60
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - name: Upload to ECR and tag
#         uses: alphagov/di-devplatform-upload-action-ecr@1.0.1
#         with:
#           role-to-assume-arn: ${{ secrets.BUILD_ROLE_TO_ASSUME }}
#           container-sign-kms-key-arn: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
#           ecr-repo-name: ${{ secrets.BUILD_ECR_REPOSITORY }}
#           artifact-bucket-name: ${{ secrets.BUILD_ARTIFACT_BUCKET }}

jobs:
  dockerBuildAndPush:
    name: Docker build and push
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.BUILD_ROLE_TO_ASSUME }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

      - name: Deploy SAM app to ECR
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.2.7
        with:
          artifact-bucket-name: ${{ secrets.BUILD_ARTIFACT_BUCKET }}
          container-sign-kms-key-arn: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
          working-directory: .
          docker-build-path: .
          template-file: template.yaml
          role-to-assume-arn: ${{ secrets.BUILD_ROLE_TO_ASSUME }}
          ecr-repo-name: ${{ secrets.BUILD_ECR_REPOSITORY }}
