name: Pull Request CI - Sonar
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v5
       - name: Checks if commiting secrets to repo
         uses: pre-commit/action@v3.0.1
         with:
           extra_args: "detect-secrets --all-files"
       - name: Setup nodeJS v22
         uses: actions/setup-node@v6
         with:
           node-version: 22
       - name: Install dependencies
         run: npm ci
       - name: Run lint
         run: npm run lint
       - name: Run build
         run: npm run build
       - name: Run test and write coverage
         run: npm run test
       - name: "Run SonarCloud Scan"
         if: ${{ success() && github.actor != 'dependabot[bot]' }}
         uses: SonarSource/sonarqube-scan-action@v5.3.1
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
